repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: ['--profile=black']

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=88
          - --extend-ignore=E203
          - --exclude=settings.py

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        args: [--strict, --ignore-missing-imports, --disallow-subclassing-any]
        additional_dependencies: [
          django-stubs==5.0.4,
          django-stubs-ext==5.0.4,
          python-dotenv==1.0.1,
          django-cors-headers==4.4.0,
          djangorestframework==3.15.2,
          django-quill-editor==0.1.40,
        ]
