import os

PROJECT_CONFIGS = {
    "CUSTOM_CORS_ALLOWED_ORIGINS": os.getenv("CUSTOM_CORS_ALLOWED_ORIGINS"),
    "API_VERSION": os.getenv("API_VERSION"),
    "DEBUG": os.getenv("DEBUG"),
    "ALLOWED_HOST": os.getenv("ALLOWED_HOST"),
    "USE_EXTERNAL_LOGGER": os.getenv("USE_EXTERNAL_LOGGER"),
}