# Generated by Django 5.0.6 on 2024-07-12 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        # migrations.CreateModel(
        #     name='Product',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('created_on', models.DateTimeField(auto_now=True)),
        #         ('updated_on', models.DateTimeField(auto_now_add=True)),
        #         ('name', models.CharField(blank=True, max_length=255)),
        #         ('price', models.FloatField(default=0.0)),
        #         ('high_price', models.FloatField(default=0.0)),
        #         ('min_price', models.FloatField(default=0.0)),
        #         ('url', models.URLField(blank=True)),
        #         ('for_sale', models.BooleanField(default=True)),
        #         # ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_feature_image', to='products.image')),
        #         # ('images', models.ManyToManyField(blank=True, related_name='product_images', to='products.image')),
        #         ('product_type', models.ManyToManyField(related_name='product_menus', to='products.menu')),
        #         ('colors', models.ManyToManyField(blank=True, related_name='product_colors', to='products.productcolor')),
        #         # ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_currency', to='products.productcurrency')),
        #         ('description', models.ManyToManyField(related_name='product_description', to='products.productdescription')),
        #         ('product_locations', models.ManyToManyField(blank=True, related_name='product_locations', to='products.productlocation')),
        #         ('sizes', models.ManyToManyField(blank=True, related_name='product_sizes', to='products.productsize')),
        #     ],
        #     options={
        #         'abstract': False,
        #     },
        # ),
    ]
