# Generated by Django 5.0.6 on 2024-07-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_image_productcolor_productcurrency_and_more'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Image',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('created_on', models.DateTimeField(auto_now=True)),
        #         ('updated_on', models.DateTimeField(auto_now_add=True)),
        #         ('name', models.CharField(blank=True, max_length=255)),
        #         ('image_path', models.URLField(blank=True)),
        #         ('image_type', models.CharField(blank=True, max_length=100)),
        #         ('image_width', models.IntegerField(default=0)),
        #         ('image_height', models.IntegerField(default=0)),
        #         ('image_size', models.CharField(blank=True, max_length=50)),
        #         ('image_color', models.CharField(blank=True, max_length=50)),
        #         ('image_number', models.IntegerField(default=0)),
        #     ],
        #     options={
        #         'abstract': False,
        #     },
        # ),
        # migrations.CreateModel(
        #     name='ProductColor',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('created_on', models.DateTimeField(auto_now=True)),
        #         ('updated_on', models.DateTimeField(auto_now_add=True)),
        #         ('title', models.CharField(max_length=500)),
        #         ('disabled', models.BooleanField(default=False)),
        #     ],
        #     options={
        #         'verbose_name_plural': 'Product Colors',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='ProductCurrency',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('created_on', models.DateTimeField(auto_now=True)),
        #         ('updated_on', models.DateTimeField(auto_now_add=True)),
        #         ('name', models.CharField(max_length=50)),
        #         ('symbol', models.CharField(max_length=10)),
        #     ],
        #     options={
        #         'verbose_name_plural': 'Product Currencies',
        #     },
        # # ),
        # migrations.CreateModel(
        #     name='ProductDescription',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('created_on', models.DateTimeField(auto_now=True)),
        #         ('updated_on', models.DateTimeField(auto_now_add=True)),
        #         ('text', models.CharField(max_length=500)),
        #     ],
        #     options={
        #         'verbose_name_plural': 'Product Description',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='ProductLocation',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('created_on', models.DateTimeField(auto_now=True)),
        #         ('updated_on', models.DateTimeField(auto_now_add=True)),
        #         ('name', models.CharField(max_length=50)),
        #     ],
        #     options={
        #         'verbose_name_plural': 'Product Locations',
        #     },
        # ),
        # migrations.RemoveField(
        #     model_name='product',
        #     name='sizes',
        # ),
        # migrations.DeleteModel(
        #     name='ProductSize',
        # ),
    ]
