# Generated by Django 5.0.6 on 2024-07-12 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_image_productcolor_productcurrency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('image_path', models.URLField(blank=True)),
                ('image_type', models.CharField(blank=True, max_length=100)),
                ('image_width', models.IntegerField(default=0)),
                ('image_height', models.IntegerField(default=0)),
                ('image_size', models.CharField(blank=True, max_length=50)),
                ('image_color', models.CharField(blank=True, max_length=50)),
                ('image_number', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=500)),
                ('disabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Product Colors',
            },
        ),
        migrations.CreateModel(
            name='ProductCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Product Currencies',
            },
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Product Description',
            },
        ),
        migrations.CreateModel(
            name='ProductLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Product Locations',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('price', models.FloatField(default=0.0)),
                ('high_price', models.FloatField(default=0.0)),
                ('min_price', models.FloatField(default=0.0)),
                ('url', models.URLField(blank=True)),
                ('for_sale', models.BooleanField(default=True)),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_feature_image', to='products.image')),
                ('images', models.ManyToManyField(blank=True, related_name='product_images', to='products.image')),
                ('product_type', models.ManyToManyField(related_name='product_menus', to='products.menu')),
                ('colors', models.ManyToManyField(blank=True, related_name='product_colors', to='products.productcolor')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_currency', to='products.productcurrency')),
                ('description', models.ManyToManyField(related_name='product_description', to='products.productdescription')),
                ('product_locations', models.ManyToManyField(blank=True, related_name='product_locations', to='products.productlocation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
