# Generated by Django 5.0.6 on 2024-07-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_image_productcolor_productcurrency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_color',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_number',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_size',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_width',
        ),
    ]
