# Generated by Django 5.0.6 on 2024-07-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_image_image_color_remove_image_image_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='image',
            name='image_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='image_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='image_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='image',
            name='image_width',
            field=models.IntegerField(default=0),
        ),
    ]
