# Generated by Django 5.0.6 on 2024-07-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_image_image_color_image_image_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_width',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
