# Generated by Django 5.0.6 on 2024-07-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_image_image_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_height',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_width',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
