# Generated by Django 5.0.6 on 2024-07-12 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_image_image_height_alter_image_image_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_color',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_number',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_size',
        ),
    ]
