# Generated by Django 5.0.6 on 2024-08-05 10:38

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_productsizetitle_disabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=django_quill.fields.QuillField(blank=True),
        ),
    ]
