# Generated by Django 5.0.6 on 2024-08-05 10:51

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_remove_product_description_product_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductDescription',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
