# Generated by Django 5.0.6 on 2024-08-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_rename_cart_item_productcart_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcart',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
