# Generated by Django 5.0.6 on 2024-08-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0028_productcart_total_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="description",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="menu",
            name="path",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
